### ISSUE TITLE
Feature Request - show TODOs in a tree view panel

### ISSUE THREAD

**Issue by Gruntfuggly** [mt40/vscode-todo-parser#63]
It would be really nice to parse all the files in the workspace and put the output in a tree view panel.

**Comment by nealoke** [comment]
Yep I'm totally missing this as well :)

**Comment by sarkistlt** [comment]
+1

**Comment by tutley** [comment]
+1

Put it in the explorer, with a link to the file and the number of TODOs within

**Comment by ajoslin103** [comment]
This is shown in the README.md, but doesn't work for me -- is that because of the new multiple root support?

**Comment by Gruntfuggly** [comment]
I think the image in the README.md is misleading - it looks like the project folder is called 'todo' which is actually what is shown.

I'm currently implementing a new TODO viewer using ripgrep so it should be nice and fast - and it will display the results in a tree view 8-)

**Comment by Gruntfuggly** [comment]
Doesn't look like there is any activity on this - if anybody finds themselves here, I ended up writing my own extension to do this: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
