### ISSUE TITLE
MultiLine TODOs in Python

### ISSUE THREAD

**Issue by ghostku** [mt40/vscode-todo-parser#81]
I tried to create a multiline TODO in Python, but it doesn't work.

I tried:

    # TODO: first line
    # Second line

    '''
    TODO: First line
    Second line
    '''

but it doesn't work. Should it?

**Comment by mt40** [comment]
Hi @ghostku , thanks for trying out my extension but I don't have time to maintain it anymore :(
Please use [todo-tree](https://github.com/Gruntfuggly/todo-tree), it's much better
